### ISSUE TITLE
Technique to contain jagged edges in side-by-side panoramas?

### ISSUE THREAD

**Issue by codetricity** [dariocavada/panorama_viewer#11]
I have two panoramas side by side to compare image transformation.  The second Panorama in the row shows a jagged edge. What is the best way to constrain the edge?

<img width="849" alt="image" src="https://github.com/dariocavada/panorama_viewer/assets/5799860/b7813ccd-5014-4095-952f-2c0eb4ca0f08">

```dart
          child: Row(
            children: [
              SizedBox(
                width: screenWidth / 2,
                height: screenHeight,
                child: PanoramaViewer(
                  key: _panoAKey,
                  child: Image.asset('assets/images/enhanced.jpg'),
                ),
              ),
              SizedBox(
                width: screenWidth / 2,
                height: screenHeight,
                child: PanoramaViewer(
                  child: Image.asset('assets/images/dark.jpg'),
                ),
              ),
            ],
          ),
```

**Comment by dariocavada** [comment]
I'll try ASAP.
Did you find this issue for the web or for iOS/Android ?

**Comment by codetricity** [comment]
Android Pixel 3a

![image](https://github.com/dariocavada/panorama_viewer/assets/5799860/b59af5dd-27f0-47e5-b6b2-0ad77c8a9248)

This example shows a blank square box on the left to make the jagged edge more visible.  There may be a simple way to contain the PanoramaViewer with a standard Flutter widget constraint.  I don't know Flutter that well.  This might not be a problem with the panorama_viewer code.  The solution might be a constraint that I could apply on a Flutter widget that has PanoramaViewer as a child.  Maybe SizedBox has a better way to constrain the PanoramaViewer widget?

![jagged_2](https://github.com/dariocavada/panorama_viewer/assets/5799860/2343c656-980e-4cb9-adae-aff175dbd500)

```dart
Row(
    children: [
      SizedBox(
        width: screenWidth / 2,
        height: screenHeight,
        child: PanoramaViewer(
          key: _panoAKey,
          child: Image.asset(
              'assets/images/public/ricoh_carlsbad.jpg'),
        ),
      ),
      SizedBox(
        width: screenWidth / 2,
        height: screenHeight,
        child: PanoramaViewer(
          key: _panoBKey,
          child: Image.asset(
              'assets/images/public/ricoh_carlsbad_oilify.jpg'),
        ),
      ),
    ],
  ),
```

**Comment by dariocavada** [comment]
I've tried with your code (using the panoramas I have in the example folder) and I don't see the error...

I've updated github examples with example5 side by side panoramas:
`example/lib/screens/example_screen_5.dart`

And the screenshot of what I see on my Android Redmi Note 10:
![side-by-side-example](https://github.com/dariocavada/panorama_viewer/assets/4304176/c8e93abd-c381-4a98-b32a-952f1a41571a)

Maybe is the format of the photos ? or something else in your code ?
Could you please share the full code and the photos so I can check and replicate the error ?

**Comment by codetricity** [comment]
Do you see an edge if you rotate the right image

![image](https://github.com/dariocavada/panorama_viewer/assets/5799860/b92835e1-9c18-493f-b32a-887cce308b50)

Here's another view of the problem.


![image](https://github.com/dariocavada/panorama_viewer/assets/5799860/a53d81af-7728-4bd5-8570-39f34e6340db)


[Screencast from 04-26-2024 10:57:58 AM.webm](https://github.com/dariocavada/panorama_viewer/assets/5799860/4cec2380-8d13-45d8-a7eb-2b522ffe37e7)

BTW, thank you again for keeping this project alive.  It's a very useful viewer for the Flutter community. Also, thanks for the examples directory.  It's really helpful for me.

**Comment by dariocavada** [comment]
Updated the example_screen_5 with ClipRect:
https://github.com/dariocavada/panorama_viewer/blob/main/example/lib/screens/example_screen_5.dart

**Comment by codetricity** [comment]
thank you.  I really appreciate your help.  This has been bothering me for a while.  I didn't know about ClipRect.  You really helped out my project.  Have a wonderful weekend.  Really appreciate all your work.
