### ISSUE TITLE
Longitude and latitude initialization

### ISSUE THREAD

**Issue by dstudzinski** [dariocavada/panorama_viewer#2]
Hi,

It's great that you forked and take care of this awesome plugin.
I checked that your fork has the same issue as original one which is lat/long initialization.
For example -180 and 180 longitude should position image in the same way but it's not.
It's already solved in another fork (not published to dart repository) https://github.com/zesage/panorama/compare/master...deckerst:aves_panorama:aves

Maybe you can take some fixes from PRs in original repo or from aves fork?

**Comment by dariocavada** [comment]
fixed in the updated  version 1.0.3
