### ISSUE TITLE
Re-render of Panorama results in blank screen

### ISSUE THREAD

**Issue by dstudzinski** [dariocavada/panorama_viewer#3]
Hi,

I've found an issue with Panorama when I tried to update lat/lon after user click.
I wanted to center place where user clicked.

If you change lat/long (stored in widget state) nothing happens (Panorama is not updated) so I added key to the widget.

If you add key to the widget and change it to force re-render when new lat/lon is set, blank/white screen is rendered instead of texture (but panorama works, onTap functions are called properly and you can 'rotate' view).
Strange thing is that's an issue only for small images.

When you get blank screen and then replace image then everything works again.

It looks like some kind of race condition because eg small images load faster.

I prepared demo which shows the problem (I use aves fork because it has fixed lat/lon initialization but the problem is visible also with panorama_viewer https://github.com/zesage/panorama/compare/master...deckerst:aves_panorama:aves )

Link to example which shows the problem: https://github.com/dstudzinski/flutter_empty_project/blob/panorama_white_screen/lib/main.dart
1. When you start app with all checkboxes unselected nothing happens when you click somewhere on panorama,
2. when you select first checkbox to generate new key, panorama is moved to center place which was clicked,
3. when you select second checkbox to use small image and click somewhere you will get blank screen,
4. when you select third checkbox and click somewhere (you can click on blank screen as Panorama works anyway) panorama image will be rotated/moved after click but dummy image blinks for brief moment.

Small image is a rescaled version of big image (only resolution was changed in Preview app for Mac).

I started to learn Dart and Flutter recently so I don't know how to fix it yet but I'm willing to help with it.

**Comment by execOQ** [comment]
Hey. The same problem with panorama zooming. I have added a mouse scroll listener and when I change the scale of the widget it displays a blank screen.

@dstudzinski Haven't found any solution?

**Comment by dariocavada** [comment]
update to the new version 1.0.3 and look at the example4: 
https://github.com/dariocavada/panorama_viewer/blob/main/example/lib/screens/example_screen_4.dart
