### ISSUE TITLE
Control panorama position/orientation with external UI (sliders, buttons...)

### ISSUE THREAD

**Issue by KristijanZic** [dariocavada/panorama_viewer#4]
I'd like to create 2 scroll bars that would control the orientation/position of the panorama from outside of the panorama widget.

Is that possible using this package, how would I go about implementing that?

I was trying with the panorama package but I just can't figure out where and how to hook into it so that the panorama live updates when I drag the scrollbars.

Thank you 🙏

**Comment by Henk-Keijzer** [comment]
There is a class PanoramaState (see documentation). I think you should use that. I would like something similar (set zoom using +/- buttons), but I have no clue how to use PanoramaState. It does not show up in the example...

**Comment by dariocavada** [comment]
update to the new version 1.0.3 and look at the example4: 
https://github.com/dariocavada/panorama_viewer/blob/main/example/lib/screens/example_screen_4.dart
