### ISSUE TITLE
PanoramaViewer on Web on mobile device

### ISSUE THREAD

**Issue by GVAMDaniel** [dariocavada/panorama_viewer#5]
Hello, 
I have migrated the panorama plugin to panorama_viewer, but I am noticing that for a PWA, it works correctly on a desktop browser. However, when accessing PanoramaViewer from a mobile device browser, the application breaks. 
This was already happening with the panorama plugin, and I'm not sure if there is a way to make it work correctly on mobile browsers or if you are planning to implement web functionality. 
Currently, there is no other plugin that does this, and it would sell very well. 
Thank you in advance.

**Comment by dariocavada** [comment]
It works just for iOS and Android. Also dependencies works just for iOS and Android.

**Comment by codetricity** [comment]
@GVAMDaniel FYI, I just ran a test and it works on mobile web if you build with wasm on the configurations listed below.  Likely usable for an internal demo if you can control the browser that the staff uses.  For example, if you build for mobile, but you want to show a result to your staff without having to share the iOS or Android binary, you could send the link to the PWA and tell them to use a specific browser.  I hope that Chrome on Android starts working in the future as wasm support improves in Flutter and Chrome.  Thus, the nice panorama_viewer package might be usable on mobile web without modification in the future.

I did not test with more complex apps as I've decided to wait for wasm to mature.

| browser | result |
| ------ | ------ |
| chrome 123.0 on Windows 11 Desktop | works |
| chrome 123.0 on Android | not working |
| chrome 123.0 on iOS | works |
| Firefox 124 on Android | works |
| safari on iOS | works |

https://github.com/codetricity/pano_wasm_demo
